// Question banks for the Play tab. Original writing, kept here so the games stay fresh:
// each Truth or Dare card is used once per room before any repeats, and every
// "How well do you know me?" round draws 10 new questions from the pool.
// Works for couples, friends and study groups alike; Spicy is flirty, never explicit.

const DECKS = {
  sweet: {
    truth: [
      'What’s the first thing you noticed about me?',
      'Which day with me would you happily live again?',
      'What small habit of mine do you secretly like?',
      'When did you first think “I really like this person”?',
      'What song reminds you of us?',
      'What’s a message from me you remember word for word?',
      'What’s one thing I do that always makes your day better?',
      'Which photo of us is your favourite, and why?',
      'What’s something you’ve never told me but wanted to?',
      'What did you think of me the first time we talked?',
      'What’s a moment you felt really proud of me?',
      'If we had a whole free day tomorrow, what would you plan?',
      'What’s one thing you’d like us to do more often?',
      'What’s the kindest thing anyone did for you this year?',
      'Which of my jokes actually made you laugh?',
      'What do you think I’m secretly really good at?',
      'When do you feel most like yourself around me?',
      'What’s a place you’d love to visit with me?',
      'What’s your favourite memory from our first month of knowing each other?',
      'What’s one word you’d use to describe me, and why that one?',
      'What’s something I taught you without realising?',
      'What made you smile today?',
      'Which of our inside jokes is your favourite?',
      'What’s a small gift from me you’d treasure most?',
      'What’s one thing you’re looking forward to this month?',
      'What do you miss most when we’re apart?',
      'What’s the best advice I’ve ever given you?',
      'What’s a dream you haven’t told many people?',
      'Which of my friends or family do you get along with best?',
      'What would your perfect lazy Sunday with me look like?',
      'What’s a time I surprised you in a good way?',
      'What’s something you’d like to learn together?',
      'What’s one thing you appreciate about me that you don’t say enough?',
      'What’s your favourite way to spend time on a call with me?',
      'What tradition would you like us to start?',
    ],
    dare: [
      'Send a voice note saying three things you like about me.',
      'Do your best impression of me for 10 seconds.',
      'Set a photo of us as your lock screen until tomorrow.',
      'Plan our next meet-up out loud in 30 seconds.',
      'Write a two-line poem about me right now and read it out.',
      'Sing the chorus of the first song that comes to mind.',
      'Tell me a compliment using only emojis in the chat.',
      'Describe our friendship or relationship as a movie title.',
      'Show me the last thing that made you laugh on your phone.',
      'Give me a nickname for the rest of the game.',
      'Share your current phone wallpaper and explain it.',
      'Do your happiest dance for 15 seconds.',
      'Read out the last message you sent me in a dramatic voice.',
      'Name five things you’d pack for a trip with me — fast.',
      'Draw me in 20 seconds and hold it up to the camera.',
      'Tell me about your day as if you’re a news reporter.',
      'Send me a song you think I’d love, right now.',
      'Make up a secret handshake we can do on camera.',
      'Show the oldest photo of us (or with me) on your phone.',
      'Say “I appreciate you” in three different accents.',
      'Recreate a selfie we took together, on your own.',
      'Tell a 30-second story about how we met, but make it a fairy tale.',
      'Write my name in the air with your nose.',
      'Pick a date for our next call-movie night and add it to Plans.',
      'Send a sticker that describes your mood right now.',
      'Name three things on my wish list (guess if you don’t know).',
      'Give a 20-second speech about why I’m a great friend.',
      'Hum a song and let me guess it.',
      'Show me your favourite thing in the room you’re in.',
      'Teach me something in under a minute.',
    ],
  },
  fun: {
    truth: [
      'What’s the most embarrassing song you know every word of?',
      'What’s the strangest thing you searched online this week?',
      'Which of your friends would survive longest in a zombie film?',
      'What’s your most irrational fear?',
      'What’s the worst haircut you’ve ever had?',
      'What’s a food combination you love that others find gross?',
      'What’s the silliest thing you’ve cried at?',
      'What’s the longest you’ve gone without showering?',
      'What app do you waste the most time on?',
      'What’s the most childish thing you still do?',
      'Who was your first celebrity crush?',
      'What’s the most useless talent you have?',
      'What’s a rule you broke as a kid and never got caught for?',
      'What’s the weirdest dream you remember?',
      'What would your autobiography be called?',
      'If you could swap lives with someone for a day, who?',
      'What’s your guilty-pleasure show?',
      'What’s the funniest thing that happened to you in school or college?',
      'What’s a word you always spell wrong?',
      'Which emoji do you overuse?',
      'What’s the most expensive thing you’ve broken?',
      'What’s the last lie you told?',
      'What’s your go-to excuse for being late?',
      'What’s the worst gift you’ve pretended to like?',
      'What would you do if you were invisible for a day?',
      'What’s the most awkward thing you’ve said to a teacher or boss?',
      'Which fictional character are you most like?',
      'What’s the cringiest post you’ve ever made?',
      'What’s your hidden snack stash?',
      'If animals could talk, which one would be the rudest?',
      'What’s the most random thing in your bag right now?',
      'What’s the worst thing you’ve cooked?',
      'Which song do you sing in the shower?',
      'What’s a hill you’re willing to die on?',
      'What’s the funniest autocorrect fail you’ve sent?',
    ],
    dare: [
      'Talk in an accent until your next turn.',
      'Show the last photo in your gallery.',
      'Do 10 squats while saying the alphabet.',
      'Do your best runway walk across the room.',
      'Speak only in questions until your next turn.',
      'Balance a spoon on your nose for 10 seconds.',
      'Do your best evil laugh.',
      'Act out a movie scene — the others guess the film.',
      'Talk like a pirate for the next two minutes.',
      'Do an impression of a famous person — we guess who.',
      'Try to lick your elbow.',
      'Say a tongue twister three times fast.',
      'Pretend to be a cat until your next turn.',
      'Show the most recent screenshot on your phone.',
      'Make a weather report for your room.',
      'Wear a sock on your hand as a puppet for the next round.',
      'Do your best robot dance for 20 seconds.',
      'Narrate what you’re doing like a nature documentary for 30 seconds.',
      'Draw a self-portrait with your eyes closed.',
      'Sing everything you say until your next turn.',
      'Do 15 jumping jacks.',
      'Show us the weirdest thing within arm’s reach.',
      'Invent a new dance move and name it.',
      'Read the last text in your notes app out loud.',
      'Make the most dramatic sneeze you can.',
      'Give a two-minute TED talk on something you know nothing about.',
      'Try to touch your toes and hold it for 15 seconds.',
      'Rap your answer to the next question you’re asked.',
      'Tell a joke — if nobody laughs, tell another.',
      'Put on the nearest hat or towel turban for the rest of the game.',
    ],
  },
  spicy: {
    truth: [
      'Which outfit of mine do you like most?',
      'What’s your favourite way I say your name?',
      'Describe your ideal night in with me in five words.',
      'What was the moment you first felt butterflies?',
      'What’s the most romantic thing you’ve imagined us doing?',
      'Which of my features do you notice first?',
      'What’s a compliment you’ve wanted to give me but held back?',
      'What’s your idea of a perfect date with me?',
      'When did you last think about me and smile?',
      'What song would you play on our slow-dance?',
      'What’s the cutest thing I do without noticing?',
      'What’s a little thing I could do that would make you melt?',
      'Have you ever practised what to say to me?',
      'What’s your favourite photo of me?',
      'What do you daydream about when you miss me?',
      'Which of my messages made your heart skip?',
      'What’s the most attractive quality someone can have?',
      'Where would you take me for a surprise weekend?',
      'What’s one thing about me you find irresistible?',
      'What would you write in a love note to me today?',
    ],
    dare: [
      'Whisper something sweet — no laughing.',
      'Give me your best wink on camera.',
      'Tell me the moment you knew you liked me, slowly.',
      'Describe our perfect date night in one breath.',
      'Hold eye contact with me for 20 seconds.',
      'Send me a selfie with your most charming smile.',
      'Say three things you find attractive about me.',
      'Serenade me with one line of a love song.',
      'Blow a kiss to the camera in slow motion.',
      'Tell me what you’d cook for our dinner date.',
      'Describe how you’d greet me if I walked in right now.',
      'Read my name like it’s the title of a romance novel.',
      'Pick the song for our next slow dance and play it.',
      'Give me your best pick-up line.',
      'Tell me where you’d like our next date to be — with details.',
      'Show me the outfit you’d wear on a date with me.',
      'Make a heart with your hands and hold it for 10 seconds.',
      'Describe me using only three words, slowly.',
      'Send a voice note saying goodnight the sweetest way you can.',
      'Plan a surprise for me — tell me only one clue.',
    ],
  },
};

// "How well do you know me?" — q is asked about someone, you is asked to the person themself.
const QUIZ = [
  { q: 'What would {name} order at midnight?', you: 'What would you order at midnight?', opts: ['Maggi', 'Pizza', 'Ice cream', 'Nothing — asleep'] },
  { q: '{name}’s dream holiday?', you: 'Your dream holiday?', opts: ['Mountains', 'Beach', 'Big city', 'Road trip'] },
  { q: 'What annoys {name} most?', you: 'What annoys you most?', opts: ['Late replies', 'Loud chewing', 'Spoilers', 'Slow walkers'] },
  { q: '{name}’s comfort movie?', you: 'Your comfort movie?', opts: ['A rom-com', 'Animated', 'Thriller', 'Old classic'] },
  { q: 'How does {name} spend a free Sunday?', you: 'How do you spend a free Sunday?', opts: ['Sleeping in', 'Out with friends', 'Binge-watching', 'A hobby project'] },
  { q: '{name}’s go-to drink?', you: 'Your go-to drink?', opts: ['Chai', 'Coffee', 'Juice', 'Just water'] },
  { q: 'What would {name} save first in a fire?', you: 'What would you save first in a fire?', opts: ['Phone', 'Photos', 'A pet or plant', 'Laptop'] },
  { q: '{name}’s biggest fear?', you: 'Your biggest fear?', opts: ['Spiders', 'Heights', 'Being alone', 'Public speaking'] },
  { q: 'Which superpower would {name} pick?', you: 'Which superpower would you pick?', opts: ['Teleport', 'Read minds', 'Fly', 'Freeze time'] },
  { q: 'What makes {name} feel cared for most?', you: 'What makes you feel cared for most?', opts: ['Kind words', 'Time together', 'Little gifts', 'Hugs'] },
  { q: 'Is {name} a morning person?', you: 'Are you a morning person?', opts: ['Up at sunrise', 'Fine after coffee', 'Only after noon', 'Night owl forever'] },
  { q: '{name}’s favourite season?', you: 'Your favourite season?', opts: ['Summer', 'Monsoon', 'Winter', 'Spring'] },
  { q: 'What does {name} do when stressed?', you: 'What do you do when stressed?', opts: ['Eat snacks', 'Sleep', 'Go for a walk', 'Talk to someone'] },
  { q: '{name}’s ideal pet?', you: 'Your ideal pet?', opts: ['Dog', 'Cat', 'Fish or bird', 'No pets, thanks'] },
  { q: 'Where would {name} rather live?', you: 'Where would you rather live?', opts: ['Big city', 'Small town', 'By the sea', 'In the hills'] },
  { q: 'What’s {name}’s phone battery usually at?', you: 'What’s your phone battery usually at?', opts: ['Always 80%+', 'Around half', 'Living on 10%', 'Constantly charging'] },
  { q: 'How does {name} reply to messages?', you: 'How do you reply to messages?', opts: ['Instantly', 'Within an hour', 'Hours later', 'Reads and forgets'] },
  { q: '{name}’s favourite cuisine?', you: 'Your favourite cuisine?', opts: ['Indian', 'Italian', 'Chinese', 'Mexican'] },
  { q: 'Which would {name} rather give up?', you: 'Which would you rather give up?', opts: ['Social media', 'Sweets', 'Coffee or tea', 'Streaming'] },
  { q: 'How does {name} handle a rainy day?', you: 'How do you handle a rainy day?', opts: ['Chai and pakoras', 'Dance in the rain', 'Stay in bed', 'Annoyed at the weather'] },
  { q: '{name}’s karaoke pick?', you: 'Your karaoke pick?', opts: ['Bollywood hit', 'Pop anthem', 'Rock classic', 'Refuses to sing'] },
  { q: 'What kind of traveller is {name}?', you: 'What kind of traveller are you?', opts: ['Plans every hour', 'Goes with the flow', 'Food first', 'Photos first'] },
  { q: 'How does {name} take their coffee or tea?', you: 'How do you take your coffee or tea?', opts: ['Very sweet', 'A little sugar', 'No sugar', 'Doesn’t drink it'] },
  { q: '{name}’s hidden talent?', you: 'Your hidden talent?', opts: ['Cooking', 'Singing', 'Drawing', 'Remembering everything'] },
  { q: 'What does {name} do first after waking up?', you: 'What do you do first after waking up?', opts: ['Check phone', 'Drink water', 'Snooze again', 'Stretch or exercise'] },
  { q: 'Which game would {name} win?', you: 'Which game would you win?', opts: ['Ludo', 'Chess', 'Cards', 'A quiz'] },
  { q: '{name}’s idea of a perfect gift?', you: 'Your idea of a perfect gift?', opts: ['Something handmade', 'An experience', 'Tech or gadgets', 'Books'] },
  { q: 'How tidy is {name}’s room?', you: 'How tidy is your room?', opts: ['Spotless', 'Tidy-ish', 'Organised chaos', 'Please don’t look'] },
  { q: 'Which would {name} pick for a weekend?', you: 'Which would you pick for a weekend?', opts: ['Trek', 'Spa day', 'Movie marathon', 'Party'] },
  { q: 'What’s {name}’s most-used app?', you: 'What’s your most-used app?', opts: ['WhatsApp', 'Instagram', 'YouTube', 'Something for work'] },
  { q: 'How does {name} celebrate good news?', you: 'How do you celebrate good news?', opts: ['Tell everyone', 'Treat myself', 'Keep it quiet', 'Call one person first'] },
  { q: 'Which dessert can {name} never refuse?', you: 'Which dessert can you never refuse?', opts: ['Gulab jamun', 'Chocolate cake', 'Ice cream', 'Cheesecake'] },
  { q: 'What would {name} do with a surprise ₹10,000?', you: 'What would you do with a surprise ₹10,000?', opts: ['Save it', 'Shopping', 'A trip', 'Treat friends'] },
  { q: '{name}’s study or work style?', you: 'Your study or work style?', opts: ['Early and steady', 'Last-minute sprint', 'With music on', 'Total silence'] },
  { q: 'How does {name} fall asleep?', you: 'How do you fall asleep?', opts: ['Instantly', 'Scrolling first', 'Music or podcast', 'Overthinking'] },
  { q: 'Which would {name} rather be?', you: 'Which would you rather be?', opts: ['Famous', 'Rich', 'Wise', 'Always happy'] },
  { q: '{name}’s favourite way to stay in touch?', you: 'Your favourite way to stay in touch?', opts: ['Texts', 'Voice notes', 'Video calls', 'Memes'] },
  { q: 'What would {name} name a pet goldfish?', you: 'What would you name a pet goldfish?', opts: ['Something funny', 'A food name', 'A human name', 'Goldie, obviously'] },
  { q: 'Which decade would {name} live in?', you: 'Which decade would you live in?', opts: ['The 70s', 'The 90s', 'Right now', 'The future'] },
  { q: 'How does {name} act when hungry?', you: 'How do you act when hungry?', opts: ['Grumpy', 'Quiet', 'Talks about food nonstop', 'Doesn’t notice'] },
  { q: '{name}’s ideal birthday?', you: 'Your ideal birthday?', opts: ['Big party', 'Small dinner', 'A trip', 'A quiet day'] },
  { q: 'What would {name} binge-watch first?', you: 'What would you binge-watch first?', opts: ['A crime series', 'A sitcom', 'Anime', 'A reality show'] },
  { q: 'How does {name} pick a restaurant?', you: 'How do you pick a restaurant?', opts: ['Same old favourite', 'Reads reviews', 'Whatever’s closest', 'Lets others decide'] },
  { q: 'Which sport would {name} watch?', you: 'Which sport would you watch?', opts: ['Cricket', 'Football', 'Tennis', 'None at all'] },
  { q: '{name}’s reaction to a spider?', you: 'Your reaction to a spider?', opts: ['Scream', 'Calmly move it outside', 'Ask someone else', 'Pretend it’s not there'] },
  { q: 'What does {name} collect?', you: 'What do you collect?', opts: ['Photos', 'Books', 'Clothes or shoes', 'Nothing really'] },
  { q: 'How does {name} prefer to apologise?', you: 'How do you prefer to apologise?', opts: ['Say sorry right away', 'Need time first', 'With a treat', 'Write a message'] },
  { q: 'Which would {name} choose for dinner?', you: 'Which would you choose for dinner?', opts: ['Home-cooked', 'Street food', 'Fancy restaurant', 'Order in'] },
  { q: '{name}’s favourite time of day?', you: 'Your favourite time of day?', opts: ['Early morning', 'Afternoon', 'Sunset', 'Late night'] },
  { q: 'How would {name} spend a snow day?', you: 'How would you spend a snow day?', opts: ['Snowball fight', 'Hot chocolate inside', 'Photos everywhere', 'Sleep through it'] },
  { q: 'What does {name} always carry?', you: 'What do you always carry?', opts: ['Earphones', 'Water bottle', 'Lip balm', 'Snacks'] },
  { q: 'Which subject did {name} enjoy most in school?', you: 'Which subject did you enjoy most in school?', opts: ['Maths or science', 'Languages', 'Art or music', 'Sports'] },
  { q: 'How does {name} feel about surprises?', you: 'How do you feel about surprises?', opts: ['Love them', 'Only small ones', 'Prefer to know', 'Hate them'] },
  { q: 'Which would {name} rather do on a call?', you: 'Which would you rather do on a call?', opts: ['Watch something', 'Play a game', 'Just talk', 'Study or work together'] },
  { q: 'What’s {name}’s love for spicy food?', you: 'What’s your love for spicy food?', opts: ['The hotter the better', 'Medium is fine', 'Mild please', 'No spice at all'] },
  { q: 'How does {name} react to a plot twist?', you: 'How do you react to a plot twist?', opts: ['Saw it coming', 'Shocked every time', 'Pause and discuss', 'Already read spoilers'] },
  { q: 'What would {name} do on a free afternoon?', you: 'What would you do on a free afternoon?', opts: ['Nap', 'Go out', 'Read', 'Learn something new'] },
  { q: 'Which festival does {name} love most?', you: 'Which festival do you love most?', opts: ['Diwali', 'Holi', 'Navratri', 'New Year'] },
  { q: 'How does {name} pack for a trip?', you: 'How do you pack for a trip?', opts: ['A week early', 'The night before', 'An hour before', 'Forgets something always'] },
  { q: 'Which would {name} rather have?', you: 'Which would you rather have?', opts: ['More time', 'More money', 'More sleep', 'More friends'] },
];

module.exports = { DECKS, QUIZ };
